// ----------------------------------------
// Constraints for tunable parameters
// ----------------------------------------

// Header
#include "Constraints.h"
#include "DeviceObjectDictionary.h"

#define NO		0	// equal to FALSE
#define YES		1	// equal to TRUE

// Constants
//
const TableItemConstraint NVConstraint[DATA_TABLE_NV_SIZE] =
									{
										{0, INT16U_MAX, X_D_DEF2},												// 0
										{1, X_D_DEF3, X_D_DEF2},												// 1
										{0, INT16U_MAX, 0},														// 2
										{0, 0, 0},																// 3
										{0, 0, 0},																// 4
										{0, 0, 0},																// 5
										{0, 0, 0},																// 6
										{0, 0, 0},																// 7
										{0, 0x3F, 0x3F},														// 8
										{CELL_V_MIN, CELL_V_MAX, CELL_V_DEF_MIN},								// 9
										{CELL_V_MIN, CELL_V_MAX, CELL_V_DEF_MAX},								// 10
										{0, 0, 0},																// 11
										{0, 0, 0},																// 12
										{FAN_TIME_MIN, FAN_TIME_MAX, FAN_TIME_DEF},								// 13
										{FAN_TIME_MIN, FAN_TIME_MAX, FAN_TIME_DEF},								// 14
										{0, 1, 0},																// 15
										{0, 0, 0},																// 16
										{NO, YES, YES},															// 17
										{NO, YES, YES},															// 18
										{NO, YES, YES},															// 19
										{0, 0, 0},																// 20
										{0, INT16U_MAX, 0},														// 21
										{NO, YES, NO},															// 22
										{0, 0, 0},																// 23
										{0, 0, 0},																// 24
										{0, 0, 0},																// 25
										{0, 0, 0},																// 26
										{0, 0, 0},																// 27
										{0, 0, 0},																// 28
										{0, 0, 0},																// 29
										{0, 0, 0},																// 30
										{0, 0, 0},																// 31
										{0, 0, 0},																// 32
										{0, 0, 0},																// 33
										{0, 0, 0},																// 34
										{0, 0, 0},																// 35
										{0, 0, 0},																// 36
										{0, 0, 0},																// 37
										{0, 0, 0},																// 38
										{0, 0, 0},																// 39
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 40
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 41
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 42
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 43
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 44
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 45
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 46
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 47
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 48
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 49
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 50
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 51
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 52
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 53
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 54
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 55
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 56
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 57
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 58
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 59
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 60
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 61
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 62
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 63
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 64
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 65
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 66
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 67
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 68
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 69
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 70
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 71
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 72
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 73
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 74
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 75
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 76
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 77
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 78
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 79
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 80
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 81
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 82
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 83
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 84
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 85
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 86
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 87
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 88
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 89
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 90
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 91
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 92
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 93
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 94
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 95
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 96
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 97
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 98
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 99
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 100
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 101
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 102
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 103
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 104
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 105
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 106
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 107
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 108
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 109
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 110
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 111
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 112
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 113
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 114
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 115
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 116
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 117
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 118
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 119
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 120
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 121
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 122
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 123
										{0, 0, 0},																// 124
										{0, 0, 0},																// 125
										{0, 0, 0},																// 126
										{0, 0, 0}																// 127
									};

const TableItemConstraint VConstraint[DATA_TABLE_WP_START - DATA_TABLE_WR_START] =
									{
										{DESIRED_VOLTAGE_MIN, DESIRED_VOLTAGE_MAX, DESIRED_VOLTAGE_DEF},		// 128
										{VOLTAGE_RATE_MIN, VOLTAGE_RATE_MAX, VOLTAGE_RATE_DEF},					// 129
										{0, MAX_CSU_VOLTAGE_X10, 0},											// 130
										{0, 0, 0},																// 131
										{0, 0, 0},																// 132
										{0, 0, 0},																// 133
										{0, 0, 0},																// 134
										{0, 0, 0},																// 135
										{0, 0, 0},																// 136
										{0, 0, 0},																// 137
										{0, 0, 0},																// 138
										{0, 0, 0},																// 139
										{0, 0, 0},																// 140
										{0, 0, 0},																// 141
										{0, 0, 0},																// 142
										{0, 0, 0},																// 143
										{0, 0, 0},																// 144
										{0, 0, 0},																// 145
										{0, 0, 0},																// 146
										{0, 0, 0},																// 147
										{0, 0, 0},																// 148
										{0, 0, 0},																// 149
										{0, 1, 0},																// 150
										{0, 0, 0},																// 151
										{0, 0, 0},																// 152
										{0, 0, 0},																// 153
										{0, 0, 0},																// 154
										{0, 0, 0},																// 155
										{0, 0, 0},																// 156
										{0, 0, 0},																// 157
										{0, 0, 0},																// 158
										{0, 0, 0},																// 159
										{0, 0, 0},																// 160
										{0, 0, 0},																// 161
										{0, 0, 0},																// 162
										{0, 0, 0},																// 163
										{0, 0, 0},																// 164
										{0, 0, 0},																// 165
										{0, 0, 0},																// 166
										{0, 0, 0},																// 167
										{0, 0, 0},																// 168
										{0, 0, 0},																// 169
										{0, 0, 0},																// 170
										{0, 0, 0},																// 171
										{0, 0, 0},																// 172
										{0, 0, 0},																// 173
										{0, 0, 0},																// 174
										{0, 0, 0},																// 175
										{0, 0, 0},																// 176
										{0, 0, 0},																// 177
										{0, 0, 0},																// 178
										{0, 0, 0},																// 179
										{0, 0, 0},																// 180
										{0, 0, 0},																// 181
										{0, 0, 0},																// 182
										{0, 0, 0},																// 183
										{0, 0, 0},																// 184
										{1, MAX_CELLS_COUNT, 0},												// 185
										{0, INT16U_MAX, 0},														// 186
										{0, INT16U_MAX, 0},														// 187
										{0, 0, 0},																// 188
										{0, 0, 0},																// 189
										{0, 0, 0},																// 190
										{0, 0, 0}																// 191
									};

const TableItemConstraint ExtNVConstraint[DATA_TABLE_NV_EXT_SIZE] =
{
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 320
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 321
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 322
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 323
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 324
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 325
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 326
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 327
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 328
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 329
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 330
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 331
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 332
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 333
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 334
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 335
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 336
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 337
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 338
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 339
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 340
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 341
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 342
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 343
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 344
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 345
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 346
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 347
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 348
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 349
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 350
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 351
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 352
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 353
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 354
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 355
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 356
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 357
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 358
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 359
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 360
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 361
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 362
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 363
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 364
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 365
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 366
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 367
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 368
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 369
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 370
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 371
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 372
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 373
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 374
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 375
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 376
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 377
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 378
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 379
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 380
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 381
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 382
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 383
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 384
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 385
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 386
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 387
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 388
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 389
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 390
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 391
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 392
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 393
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 394
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 395
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 396
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 397
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 398
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 399
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 400
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 401
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 402
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 403
										{0, 0, 0},																// 404
										{0, 0, 0},																// 405
										{0, 0, 0},																// 406
										{0, 0, 0},																// 407
										{0, 0, 0},																// 408
										{0, 0, 0},																// 409
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 410
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 411
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 412
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 413
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 414
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 415
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 416
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 417
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 418
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 419
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 420
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 421
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 422
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 423
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 424
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 425
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 426
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 427
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 428
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 429
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 430
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 431
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 432
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 433
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 434
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 435
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 436
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 437
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 438
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 439
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 440
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 441
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 442
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 443
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 444
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 445
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 446
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 447
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 448
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 449
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 450
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 451
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 452
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 453
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 454
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 455
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 456
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 457
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 458
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 459
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 460
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 461
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 462
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 463
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 464
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 465
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 466
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 467
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 468
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 469
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 470
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 471
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 472
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 473
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 474
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 475
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 476
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 477
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 478
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 479
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 480
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 481
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 482
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 483
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 484
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 485
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 486
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 487
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 488
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 489
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 490
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 491
										{GATEV_CELL_MIN, GATEV_CELL_MAX, GATEV_CELL_DEF},						// 492
										{VRATE_CELL_MIN, VRATE_CELL_MAX, VRATE_CELL_DEF},						// 493
										{0, 0, 0},																// 494
										{0, 0, 0},																// 495
										{0, 0, 0},																// 496
										{0, 0, 0},																// 497
										{0, 0, 0},																// 498
										{0, 0, 0},																// 499

										{0, INT16U_MAX, 0},														// 500
										{X_D_DEF1, X_D_DEF3, X_D_DEF2},											// 501
										{0, INT16U_MAX, 0},														// 502
										{0, INT16U_MAX, 0},														// 503
										{X_D_DEF1, X_D_DEF3, X_D_DEF2},											// 504
										{0, INT16U_MAX, 0},														// 505
										{0, INT16U_MAX, 0},														// 506
										{X_D_DEF1, X_D_DEF3, X_D_DEF2},											// 507
										{0, INT16U_MAX, 0},														// 508
										{0, INT16U_MAX, 0},														// 509
										{X_D_DEF1, X_D_DEF3, X_D_DEF2},											// 510
										{0, INT16U_MAX, 0},														// 511
										{0, INT16U_MAX, 0},														// 512
										{X_D_DEF1, X_D_DEF3, X_D_DEF2},											// 513
										{0, INT16U_MAX, 0},														// 514
										{0, INT16U_MAX, 0},														// 515
										{X_D_DEF1, X_D_DEF3, X_D_DEF2},											// 516
										{0, INT16U_MAX, 0},														// 517
										{0, INT16U_MAX, 0},														// 518
										{X_D_DEF1, X_D_DEF3, X_D_DEF2},											// 519
										{0, INT16U_MAX, 0},														// 520
										{0, INT16U_MAX, 0},														// 521
										{X_D_DEF1, X_D_DEF3, X_D_DEF2},											// 522
										{0, INT16U_MAX, 0},														// 523
										{0, INT16U_MAX, 0},														// 524
										{X_D_DEF1, X_D_DEF3, X_D_DEF2},											// 525
										{0, INT16U_MAX, 0},														// 526
										{0, INT16U_MAX, 0},														// 527
										{X_D_DEF1, X_D_DEF3, X_D_DEF2},											// 528
										{0, INT16U_MAX, 0},														// 529

										{0, 0, 0},																// 530
										{0, 0, 0},																// 531
										{0, 0, 0},																// 532
										{0, 0, 0},																// 533
										{0, 0, 0},																// 534
										{0, 0, 0},																// 535
										{0, 0, 0},																// 536
										{0, 0, 0},																// 537
										{0, 0, 0},																// 538
										{0, 0, 0},																// 539
										{0, 0, 0},																// 540
										{0, 0, 0},																// 541
										{0, 0, 0},																// 542
										{0, 0, 0},																// 543
										{0, 0, 0},																// 544
										{0, 0, 0},																// 545
										{0, 0, 0},																// 546
										{0, 0, 0},																// 547
										{0, 0, 0},																// 548
										{0, 0, 0},																// 549
										{0, 0, 0},																// 550
										{0, 0, 0},																// 551
										{0, 0, 0},																// 552
										{0, 0, 0},																// 553
										{0, 0, 0},																// 554
										{0, 0, 0},																// 555
										{0, 0, 0},																// 556
										{0, 0, 0},																// 557
										{0, 0, 0},																// 558
										{0, 0, 0},																// 559
										{0, 0, 0},																// 560
										{0, 0, 0},																// 561
										{0, 0, 0},																// 562
										{0, 0, 0},																// 563
										{0, 0, 0},																// 564
										{0, 0, 0},																// 565
										{0, 0, 0},																// 566
										{0, 0, 0},																// 567
										{0, 0, 0},																// 568
										{0, 0, 0},																// 569
										{0, 0, 0},																// 570
										{0, 0, 0},																// 571
										{0, 0, 0},																// 572
										{0, 0, 0},																// 573
										{0, 0, 0},																// 574
										{0, 0, 0},																// 575
										{0, 0, 0},																// 576
										{0, 0, 0},																// 577
										{0, 0, 0},																// 578
										{0, 0, 0},																// 579
										{0, 0, 0},																// 580
										{0, 0, 0},																// 581
										{0, 0, 0},																// 582
										{0, 0, 0},																// 583
										{0, 0, 0},																// 584
										{0, 0, 0},																// 585
										{0, 0, 0},																// 586
										{0, 0, 0},																// 587
										{0, 0, 0},																// 588
										{0, 0, 0},																// 589
										{0, 0, 0},																// 590
										{0, 0, 0},																// 591
										{0, 0, 0},																// 592
										{0, 0, 0},																// 593
										{0, 0, 0},																// 594
										{0, 0, 0},																// 595
										{0, 0, 0},																// 596
										{0, 0, 0},																// 597
										{0, 0, 0},																// 598
										{0, 0, 0},																// 599
										{0, 0, 0},																// 600
										{0, 0, 0},																// 601
										{0, 0, 0},																// 602
										{0, 0, 0},																// 603
										{0, 0, 0},																// 604
										{0, 0, 0},																// 605
										{0, 0, 0},																// 606
										{0, 0, 0},																// 607
										{0, 0, 0},																// 608
										{0, 0, 0},																// 609
										{0, 0, 0},																// 610
										{0, 0, 0},																// 611
										{0, 0, 0},																// 612
										{0, 0, 0},																// 613
										{0, 0, 0},																// 614
										{0, 0, 0},																// 615
										{0, 0, 0},																// 616
										{0, 0, 0},																// 617
										{0, 0, 0},																// 618
										{0, 0, 0},																// 619
										{0, 0, 0},																// 620
										{0, 0, 0},																// 621
										{0, 0, 0},																// 622
										{0, 0, 0},																// 623
										{0, 0, 0},																// 624
										{0, 0, 0},																// 625
										{0, 0, 0},																// 626
										{0, 0, 0},																// 627
										{0, 0, 0},																// 628
										{0, 0, 0},																// 629
										{0, 0, 0},																// 630
										{0, 0, 0},																// 631
										{0, 0, 0},																// 632
										{0, 0, 0},																// 633
										{0, 0, 0},																// 634
										{0, 0, 0},																// 635
										{0, 0, 0},																// 636
										{0, 0, 0},																// 637
										{0, 0, 0},																// 638
										{0, 0, 0}																// 639
};
